#! /usr/bin/fish

if test -e ./.git/hooks/pre-commit
	sh ./.git/hooks/pre-commit
end

# adapted from the template
if command git rev-parse --verify HEAD >/dev/null 2>&1
    set against HEAD
else
    # Initial commit: diff against an empty tree object
    set against 4b825dc642cb6eb9a060e54bf8d69288fbee4904
end

# if we don't have a composer file, we must not be a php project
if not test -e composer.json
    exit 0
end

# check if we have psalm installed via phive
if not test -e tools/psalm
	command phive install psalm
end 

# check if we have a psalm.ini file
if not test -e psalm.xml
	tools/psalm --init src/
end


set staged_files (git diff-index --name-only --cached --diff-filter=ACMR $against --)

if [ $staged_files = '' ]
	exit 0
end

for staged_file in $staged_files
	# if [ (string split -m1 -r '.' "$stage_file")[1] = 'php']
	tools/psalm --show-info=false $staged_file
	if [ $status != 0 ]
		exit 1
	end
end